[profile.default]
src = "contracts"
evm_version = "cancun"   
out = "out"
libs = ["node_modules","lib"]
test = "test"
cache_path = "cache_forge"
ffi = true
optimizer = true
optimizer_runs = 1_000_000
solc_version = "0.8.26"
fs_permissions = [{ access = "read", path = "./"}]