[profile.default]
src = "contracts"
evm_version = "cancun"   
out = "out"
libs = ["node_modules","lib"]
test = "test"
cache_path = "cache_forge"
ffi = true
optimizer = true
optimizer_runs = 200
solc_version = "0.8.26"
fs_permissions = [{ access = "read", path = "./"}]

[profile.kontrol-properties]
src = "contracts"
evm_version = "cancun"
out = "out"
libs = ["node_modules","lib"]
test = "test/forge/kontrol"
script = "test/forge/kontrol"
cache_path = "cache_forge"
ffi = true
optimizer = true
optimizer_runs = 200
solc_version = "0.8.26"
fs_permissions = [{ access = "read", path = "./"}]
ast = true