[profile.default]
src = "contracts"
evm_version = "cancun"   
out = "out"
libs = ["node_modules","lib"]
test = "test"
cache_path = "cache_forge"
ffi = true
optimizer = true
optimizer_runs = 200
solc_version = "0.8.26"
fs_permissions = [{ access = "read", path = "./"}]


[profile.optimized]
out = "optimized-out"
test = "test"
via_ir = true
optimizer = true
optimizer_runs = 200

[etherscan]
unknown_chain = { key = "${TENDERLY_ACCESS_KEY}", chain = 123123, url = "${TENDERLY_VIRTUAL_TESTNET_RPC_URL}/verify/etherscan" }
