[profile.default]
src = "contracts"
evm_version = "cancun"   
out = "out"
libs = ["node_modules","lib"]
test = "test"
cache_path = "cache_forge"
optimizer = true
optimizer_runs = 200
solc_version = "0.8.24"
fs_permissions = [{ access = "read", path = "./"}]