name: Unit Test

on:
  pull_request:
    types:
      - synchronize
      - opened
      - edited
    branches:
      - main
      - tmp-changes

  push:
    paths:
      - "contracts/**"
      - "test/**"
    branches:
      - main
      - tmp-changes

jobs:
  forge-test:
    runs-on: ubuntu-latest
    name: Forge Unit Test
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Step 2: Install Foundry
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # Step 3: Enforce formatting check
      - name: Check Solidity Formatting
        run: |
          forge fmt --check || (echo "Formatting issues detected! Please run 'forge fmt' locally to fix them." && exit 1)

      # Step 4: Run unit tests
      - name: Run Tests
        run: forge test -vvv

      # Step 5: Run snapshot tests (if applicable)
      - name: Run Snapshot
        run: forge snapshot
