name: unit test
on:
  pull_request:
    types:
      - synchronize
      - opened
      - edited
    branches:
      - main
      - tmp-changes


  push:
    paths:
      - "contracts/**"
      - "test/**"
    branches:
      - main
      - tmp-changes

jobs:
  forge-test:
    runs-on: ubuntu-latest
    name: Forge unit test
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run tests
        run: forge test -vvv

      - name: Run snapshot
        run: forge snapshot